-- Prescribed Hourly Rates transcribed from the original workbook-derived migration.
-- Regulatory Table 9(a) is represented as PUBLIC_LAW_CHILDREN; Table 9(b) as OTHER_FAMILY.
-- Table 9(aa) section-31 escape rates are not stored here because the simplified model does not yet include a CPGFS escape-hourly rate table.
SET search_path TO "${flyway:defaultSchema}";

INSERT INTO phrs_rate (fee_scheme_version_id, case_category_id, court_level_id, location_id, activity_type_id, unit_type_id, amount) VALUES
((SELECT id FROM fee_scheme_version WHERE version_code='PHRS2020'), (SELECT id FROM case_category WHERE code='PUBLIC_LAW_CHILDREN'), (SELECT id FROM court_level WHERE code='HIGH_COURT'), (SELECT id FROM location WHERE code='NOT_APPLICABLE'), (SELECT id FROM activity_type WHERE code='ROUTINE_LETTER_OUT'), (SELECT id FROM unit_type WHERE code='PER_ITEM'), 4.23),
((SELECT id FROM fee_scheme_version WHERE version_code='PHRS2020'), (SELECT id FROM case_category WHERE code='PUBLIC_LAW_CHILDREN'), (SELECT id FROM court_level WHERE code='HIGH_COURT'), (SELECT id FROM location WHERE code='NOT_APPLICABLE'), (SELECT id FROM activity_type WHERE code='ROUTINE_LETTER_IN'), (SELECT id FROM unit_type WHERE code='PER_ITEM'), 2.12),
((SELECT id FROM fee_scheme_version WHERE version_code='PHRS2020'), (SELECT id FROM case_category WHERE code='PUBLIC_LAW_CHILDREN'), (SELECT id FROM court_level WHERE code='HIGH_COURT'), (SELECT id FROM location WHERE code='NOT_APPLICABLE'), (SELECT id FROM activity_type WHERE code='ROUTINE_TELEPHONE_CALL'), (SELECT id FROM unit_type WHERE code='PER_ITEM'), 4.23),
((SELECT id FROM fee_scheme_version WHERE version_code='PHRS2020'), (SELECT id FROM case_category WHERE code='PUBLIC_LAW_CHILDREN'), (SELECT id FROM court_level WHERE code='HIGH_COURT'), (SELECT id FROM location WHERE code='LONDON'), (SELECT id FROM activity_type WHERE code='PREPARATION_ATTENDANCE'), (SELECT id FROM unit_type WHERE code='PER_HOUR'), 70.07),
((SELECT id FROM fee_scheme_version WHERE version_code='PHRS2020'), (SELECT id FROM case_category WHERE code='PUBLIC_LAW_CHILDREN'), (SELECT id FROM court_level WHERE code='HIGH_COURT'), (SELECT id FROM location WHERE code='NON_LONDON'), (SELECT id FROM activity_type WHERE code='PREPARATION_ATTENDANCE'), (SELECT id FROM unit_type WHERE code='PER_HOUR'), 65.84),
((SELECT id FROM fee_scheme_version WHERE version_code='PHRS2020'), (SELECT id FROM case_category WHERE code='PUBLIC_LAW_CHILDREN'), (SELECT id FROM court_level WHERE code='HIGH_COURT'), (SELECT id FROM location WHERE code='NOT_APPLICABLE'), (SELECT id FROM activity_type WHERE code='COURT_OR_COUNSEL_CONFERENCE'), (SELECT id FROM unit_type WHERE code='PER_HOUR'), 37.13),
((SELECT id FROM fee_scheme_version WHERE version_code='PHRS2020'), (SELECT id FROM case_category WHERE code='PUBLIC_LAW_CHILDREN'), (SELECT id FROM court_level WHERE code='HIGH_COURT'), (SELECT id FROM location WHERE code='LONDON'), (SELECT id FROM activity_type WHERE code='ADVOCACY'), (SELECT id FROM unit_type WHERE code='PER_HOUR'), 70.07),
((SELECT id FROM fee_scheme_version WHERE version_code='PHRS2020'), (SELECT id FROM case_category WHERE code='PUBLIC_LAW_CHILDREN'), (SELECT id FROM court_level WHERE code='HIGH_COURT'), (SELECT id FROM location WHERE code='NON_LONDON'), (SELECT id FROM activity_type WHERE code='ADVOCACY'), (SELECT id FROM unit_type WHERE code='PER_HOUR'), 65.84),
((SELECT id FROM fee_scheme_version WHERE version_code='PHRS2020'), (SELECT id FROM case_category WHERE code='PUBLIC_LAW_CHILDREN'), (SELECT id FROM court_level WHERE code='HIGH_COURT'), (SELECT id FROM location WHERE code='NOT_APPLICABLE'), (SELECT id FROM activity_type WHERE code='TRAVEL_WAITING'), (SELECT id FROM unit_type WHERE code='PER_HOUR'), 32.18),
((SELECT id FROM fee_scheme_version WHERE version_code='PHRS2020'), (SELECT id FROM case_category WHERE code='PUBLIC_LAW_CHILDREN'), (SELECT id FROM court_level WHERE code='LOWER_COURT'), (SELECT id FROM location WHERE code='NOT_APPLICABLE'), (SELECT id FROM activity_type WHERE code='ROUTINE_LETTER_OUT'), (SELECT id FROM unit_type WHERE code='PER_ITEM'), 3.69),
((SELECT id FROM fee_scheme_version WHERE version_code='PHRS2020'), (SELECT id FROM case_category WHERE code='PUBLIC_LAW_CHILDREN'), (SELECT id FROM court_level WHERE code='LOWER_COURT'), (SELECT id FROM location WHERE code='NOT_APPLICABLE'), (SELECT id FROM activity_type WHERE code='ROUTINE_LETTER_IN'), (SELECT id FROM unit_type WHERE code='PER_ITEM'), 1.85),
((SELECT id FROM fee_scheme_version WHERE version_code='PHRS2020'), (SELECT id FROM case_category WHERE code='PUBLIC_LAW_CHILDREN'), (SELECT id FROM court_level WHERE code='LOWER_COURT'), (SELECT id FROM location WHERE code='NOT_APPLICABLE'), (SELECT id FROM activity_type WHERE code='ROUTINE_TELEPHONE_CALL'), (SELECT id FROM unit_type WHERE code='PER_ITEM'), 3.69),
((SELECT id FROM fee_scheme_version WHERE version_code='PHRS2020'), (SELECT id FROM case_category WHERE code='PUBLIC_LAW_CHILDREN'), (SELECT id FROM court_level WHERE code='LOWER_COURT'), (SELECT id FROM location WHERE code='LONDON'), (SELECT id FROM activity_type WHERE code='PREPARATION_ATTENDANCE'), (SELECT id FROM unit_type WHERE code='PER_HOUR'), 61.38),
((SELECT id FROM fee_scheme_version WHERE version_code='PHRS2020'), (SELECT id FROM case_category WHERE code='PUBLIC_LAW_CHILDREN'), (SELECT id FROM court_level WHERE code='LOWER_COURT'), (SELECT id FROM location WHERE code='NON_LONDON'), (SELECT id FROM activity_type WHERE code='PREPARATION_ATTENDANCE'), (SELECT id FROM unit_type WHERE code='PER_HOUR'), 58.41),
((SELECT id FROM fee_scheme_version WHERE version_code='PHRS2020'), (SELECT id FROM case_category WHERE code='PUBLIC_LAW_CHILDREN'), (SELECT id FROM court_level WHERE code='LOWER_COURT'), (SELECT id FROM location WHERE code='NOT_APPLICABLE'), (SELECT id FROM activity_type WHERE code='COURT_OR_COUNSEL_CONFERENCE'), (SELECT id FROM unit_type WHERE code='PER_HOUR'), 32.67),
((SELECT id FROM fee_scheme_version WHERE version_code='PHRS2020'), (SELECT id FROM case_category WHERE code='PUBLIC_LAW_CHILDREN'), (SELECT id FROM court_level WHERE code='LOWER_COURT'), (SELECT id FROM location WHERE code='NOT_APPLICABLE'), (SELECT id FROM activity_type WHERE code='ADVOCACY'), (SELECT id FROM unit_type WHERE code='PER_HOUR'), 64.35),
((SELECT id FROM fee_scheme_version WHERE version_code='PHRS2020'), (SELECT id FROM case_category WHERE code='PUBLIC_LAW_CHILDREN'), (SELECT id FROM court_level WHERE code='LOWER_COURT'), (SELECT id FROM location WHERE code='NOT_APPLICABLE'), (SELECT id FROM activity_type WHERE code='TRAVEL_WAITING'), (SELECT id FROM unit_type WHERE code='PER_HOUR'), 29.21),
((SELECT id FROM fee_scheme_version WHERE version_code='PHRS2020'), (SELECT id FROM case_category WHERE code='OTHER_FAMILY'), (SELECT id FROM court_level WHERE code='HIGH_COURT'), (SELECT id FROM location WHERE code='NOT_APPLICABLE'), (SELECT id FROM activity_type WHERE code='ROUTINE_LETTER_OUT'), (SELECT id FROM unit_type WHERE code='PER_ITEM'), 6.35),
((SELECT id FROM fee_scheme_version WHERE version_code='PHRS2020'), (SELECT id FROM case_category WHERE code='OTHER_FAMILY'), (SELECT id FROM court_level WHERE code='HIGH_COURT'), (SELECT id FROM location WHERE code='NOT_APPLICABLE'), (SELECT id FROM activity_type WHERE code='ROUTINE_LETTER_IN'), (SELECT id FROM unit_type WHERE code='PER_ITEM'), 3.15),
((SELECT id FROM fee_scheme_version WHERE version_code='PHRS2020'), (SELECT id FROM case_category WHERE code='OTHER_FAMILY'), (SELECT id FROM court_level WHERE code='HIGH_COURT'), (SELECT id FROM location WHERE code='NOT_APPLICABLE'), (SELECT id FROM activity_type WHERE code='ROUTINE_TELEPHONE_CALL'), (SELECT id FROM unit_type WHERE code='PER_ITEM'), 6.35),
((SELECT id FROM fee_scheme_version WHERE version_code='PHRS2020'), (SELECT id FROM case_category WHERE code='OTHER_FAMILY'), (SELECT id FROM court_level WHERE code='HIGH_COURT'), (SELECT id FROM location WHERE code='LONDON'), (SELECT id FROM activity_type WHERE code='PREPARATION_ATTENDANCE'), (SELECT id FROM unit_type WHERE code='PER_HOUR'), 70.56),
((SELECT id FROM fee_scheme_version WHERE version_code='PHRS2020'), (SELECT id FROM case_category WHERE code='OTHER_FAMILY'), (SELECT id FROM court_level WHERE code='HIGH_COURT'), (SELECT id FROM location WHERE code='NON_LONDON'), (SELECT id FROM activity_type WHERE code='PREPARATION_ATTENDANCE'), (SELECT id FROM unit_type WHERE code='PER_HOUR'), 65.75),
((SELECT id FROM fee_scheme_version WHERE version_code='PHRS2020'), (SELECT id FROM case_category WHERE code='OTHER_FAMILY'), (SELECT id FROM court_level WHERE code='HIGH_COURT'), (SELECT id FROM location WHERE code='NOT_APPLICABLE'), (SELECT id FROM activity_type WHERE code='COURT_OR_COUNSEL_CONFERENCE'), (SELECT id FROM unit_type WHERE code='PER_HOUR'), 37.13),
((SELECT id FROM fee_scheme_version WHERE version_code='PHRS2020'), (SELECT id FROM case_category WHERE code='OTHER_FAMILY'), (SELECT id FROM court_level WHERE code='HIGH_COURT'), (SELECT id FROM location WHERE code='LONDON'), (SELECT id FROM activity_type WHERE code='ADVOCACY'), (SELECT id FROM unit_type WHERE code='PER_HOUR'), 70.56),
((SELECT id FROM fee_scheme_version WHERE version_code='PHRS2020'), (SELECT id FROM case_category WHERE code='OTHER_FAMILY'), (SELECT id FROM court_level WHERE code='HIGH_COURT'), (SELECT id FROM location WHERE code='NON_LONDON'), (SELECT id FROM activity_type WHERE code='ADVOCACY'), (SELECT id FROM unit_type WHERE code='PER_HOUR'), 65.75),
((SELECT id FROM fee_scheme_version WHERE version_code='PHRS2020'), (SELECT id FROM case_category WHERE code='OTHER_FAMILY'), (SELECT id FROM court_level WHERE code='HIGH_COURT'), (SELECT id FROM location WHERE code='NOT_APPLICABLE'), (SELECT id FROM activity_type WHERE code='TRAVEL_WAITING'), (SELECT id FROM unit_type WHERE code='PER_HOUR'), 32.18),
((SELECT id FROM fee_scheme_version WHERE version_code='PHRS2020'), (SELECT id FROM case_category WHERE code='OTHER_FAMILY'), (SELECT id FROM court_level WHERE code='LOWER_COURT'), (SELECT id FROM location WHERE code='NOT_APPLICABLE'), (SELECT id FROM activity_type WHERE code='ROUTINE_LETTER_OUT'), (SELECT id FROM unit_type WHERE code='PER_ITEM'), 5.40),
((SELECT id FROM fee_scheme_version WHERE version_code='PHRS2020'), (SELECT id FROM case_category WHERE code='OTHER_FAMILY'), (SELECT id FROM court_level WHERE code='LOWER_COURT'), (SELECT id FROM location WHERE code='NOT_APPLICABLE'), (SELECT id FROM activity_type WHERE code='ROUTINE_LETTER_IN'), (SELECT id FROM unit_type WHERE code='PER_ITEM'), 2.70),
((SELECT id FROM fee_scheme_version WHERE version_code='PHRS2020'), (SELECT id FROM case_category WHERE code='OTHER_FAMILY'), (SELECT id FROM court_level WHERE code='LOWER_COURT'), (SELECT id FROM location WHERE code='NOT_APPLICABLE'), (SELECT id FROM activity_type WHERE code='ROUTINE_TELEPHONE_CALL'), (SELECT id FROM unit_type WHERE code='PER_ITEM'), 5.40),
((SELECT id FROM fee_scheme_version WHERE version_code='PHRS2020'), (SELECT id FROM case_category WHERE code='OTHER_FAMILY'), (SELECT id FROM court_level WHERE code='LOWER_COURT'), (SELECT id FROM location WHERE code='LONDON'), (SELECT id FROM activity_type WHERE code='PREPARATION_ATTENDANCE'), (SELECT id FROM unit_type WHERE code='PER_HOUR'), 59.40),
((SELECT id FROM fee_scheme_version WHERE version_code='PHRS2020'), (SELECT id FROM case_category WHERE code='OTHER_FAMILY'), (SELECT id FROM court_level WHERE code='LOWER_COURT'), (SELECT id FROM location WHERE code='NON_LONDON'), (SELECT id FROM activity_type WHERE code='PREPARATION_ATTENDANCE'), (SELECT id FROM unit_type WHERE code='PER_HOUR'), 54.90),
((SELECT id FROM fee_scheme_version WHERE version_code='PHRS2020'), (SELECT id FROM case_category WHERE code='OTHER_FAMILY'), (SELECT id FROM court_level WHERE code='LOWER_COURT'), (SELECT id FROM location WHERE code='NOT_APPLICABLE'), (SELECT id FROM activity_type WHERE code='COURT_OR_COUNSEL_CONFERENCE'), (SELECT id FROM unit_type WHERE code='PER_HOUR'), 32.40),
((SELECT id FROM fee_scheme_version WHERE version_code='PHRS2020'), (SELECT id FROM case_category WHERE code='OTHER_FAMILY'), (SELECT id FROM court_level WHERE code='LOWER_COURT'), (SELECT id FROM location WHERE code='LONDON'), (SELECT id FROM activity_type WHERE code='ADVOCACY'), (SELECT id FROM unit_type WHERE code='PER_HOUR'), 59.40),
((SELECT id FROM fee_scheme_version WHERE version_code='PHRS2020'), (SELECT id FROM case_category WHERE code='OTHER_FAMILY'), (SELECT id FROM court_level WHERE code='LOWER_COURT'), (SELECT id FROM location WHERE code='NON_LONDON'), (SELECT id FROM activity_type WHERE code='ADVOCACY'), (SELECT id FROM unit_type WHERE code='PER_HOUR'), 56.70),
((SELECT id FROM fee_scheme_version WHERE version_code='PHRS2020'), (SELECT id FROM case_category WHERE code='OTHER_FAMILY'), (SELECT id FROM court_level WHERE code='LOWER_COURT'), (SELECT id FROM location WHERE code='LONDON'), (SELECT id FROM activity_type WHERE code='TRAVEL_WAITING'), (SELECT id FROM unit_type WHERE code='PER_HOUR'), 28.80),
((SELECT id FROM fee_scheme_version WHERE version_code='PHRS2020'), (SELECT id FROM case_category WHERE code='OTHER_FAMILY'), (SELECT id FROM court_level WHERE code='LOWER_COURT'), (SELECT id FROM location WHERE code='NON_LONDON'), (SELECT id FROM activity_type WHERE code='TRAVEL_WAITING'), (SELECT id FROM unit_type WHERE code='PER_HOUR'), 27.90)
ON CONFLICT (fee_scheme_version_id, case_category_id, court_level_id, location_id, activity_type_id, unit_type_id) DO UPDATE
SET amount = EXCLUDED.amount;
